### ISSUE TITLE
Unknown property type: Int64Property

### ISSUE THREAD

**Issue by mcbyte-it** [sts8/GVAS-JSON-Converter#1]
I tried opening a UE4 sav file, and it gave a console error about an unknown property Int64Property.
Hope you can fix this by adding this property to the code.

**Comment by sts8** [comment]
Hi, would you mind sharing the sav file?

**Comment by mcbyte-it** [comment]
Here is a sav file (from the game Hogwarts Legacy)

[HL.zip](https://github.com/sts8/GVAS-JSON-Converter/files/12266509/HL.zip)

**Comment by sts8** [comment]
Í added the missing properties, can you try again please?

**Comment by mcbyte-it** [comment]
Thanks, great tool, I can convert the files now.
